# Simple workflow for deploying static content to GitHub Pages
name: Deploy content to Pages
on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write
concurrency: ci-${{ github.ref }} 
jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            submodules: true
            lfs: true # Fetches LFS data
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Bundle
        run: |
          npm ci 
          npm ci --prefix viewer
          NODE_ENV=production
          npm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: viewer/dist